### ISSUE TITLE
is it possible to delete part of the dataset recorded?

### ISSUE THREAD

**Issue by chenmingzhang** [sparkfun/phant-arduino#8]
I wish to have a command able to delete part of the dataset (e.g., using time range as input criteria), because many prototype project would have fiddling stage in between and that will produce some erroneous data. if user can manually delete these problematic data the quality of the data can be improved.

**Comment by elimorris** [comment]
I would like to second this request. It would be VERY helpful. We are building dataloggers that are going in the field for serious science projects and occasionally we are going to have a wayward data point as we disconnect a sensor or something (even if the programming is perfect, which assumes a lot). Then on an autoscaled plot, it is now unreadable for all time, because we have a zero that screws up the scaling that we can't get rid of. Even having a manual database procedure would be insanely helpful!

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
